# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Commented out IPython magic to ensure Python compatibility.
# ============================================================
# CSET343 LAB 1
# MULTIMODAL HEALTHCARE DATA ANALYSIS
# ============================================================


# ============================================================
# 1. INSTALL REQUIRED LIBRARIES
# ============================================================

# %pip install ucimlrepo pandas scikit-learn matplotlib seaborn numpy


# ============================================================
# 2. IMPORT LIBRARIES
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from ucimlrepo import fetch_ucirepo

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    confusion_matrix,
    classification_report,
    RocCurveDisplay
)


# ============================================================
# 3. FETCH UCI HEART DISEASE DATASET
# ============================================================

heart_disease = fetch_ucirepo(id=45)

# Features
X = heart_disease.data.features.copy()

# Target
y = heart_disease.data.targets.copy()

# Metadata
print("Dataset Metadata:")
print(heart_disease.metadata)

print("\nVariable Information:")
print(heart_disease.variables)


# ============================================================
# 4. BASIC DATASET INFORMATION
# ============================================================

print("Feature Shape:", X.shape)
print("Target Shape:", y.shape)

print("\nFirst 5 rows of features:")
display(X.head())

print("\nTarget:")
display(y.head())

print("\nMissing values in features:")
print(X.isnull().sum())

print("\nMissing values in target:")
print(y.isnull().sum())


# ============================================================
# 5. CONVERT TARGET INTO BINARY CLASSIFICATION
# ============================================================

# Convert target DataFrame to Series
y = y.iloc[:, 0]

# 0 = No disease
# 1, 2, 3, 4 = Disease present
y = (y > 0).astype(int)

print("Binary Target Distribution:")
print(y.value_counts())

sns.countplot(x=y)
plt.title("Distribution of Heart Disease")
plt.xlabel("Heart Disease (0 = No, 1 = Yes)")
plt.ylabel("Count")
plt.show()


# ============================================================
# 6. CREATE COMPLETE DATAFRAME
# ============================================================

df = X.copy()
df["target"] = y

display(df.head())

print(df.info())

print(df.describe())


# ============================================================
# 7. CHECK MISSING VALUES
# ============================================================

missing_values = df.isnull().sum()

print("Missing Values:")
print(missing_values[missing_values > 0])


# ============================================================
# 8. FEATURE DISTRIBUTION
# ============================================================

X.hist(figsize=(15, 12), bins=20)

plt.suptitle(
    "Feature Distributions",
    fontsize=16
)

plt.tight_layout()
plt.show()


# ============================================================
# 9. CORRELATION HEATMAP
# ============================================================

numeric_df = df.select_dtypes(include=np.number)

plt.figure(figsize=(14, 10))

sns.heatmap(
    numeric_df.corr(),
    cmap="coolwarm",
    center=0,
    annot=True
)

plt.title("Correlation Heatmap")
plt.show()


# ============================================================
# 10. PREPARE X AND y FOR MACHINE LEARNING
# ============================================================

X = df.drop("target", axis=1)
y = df["target"]

print("X Shape:", X.shape)
print("y Shape:", y.shape)


# ============================================================
# 11. TRAIN-TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training Samples:", X_train.shape[0])
print("Testing Samples:", X_test.shape[0])


# ============================================================
# 12. CREATE MACHINE LEARNING PIPELINE
# ============================================================

model = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
    ("classifier", LogisticRegression(max_iter=1000))
])


# ============================================================
# 13. TRAIN LOGISTIC REGRESSION MODEL
# ============================================================

model.fit(X_train, y_train)

print("Model training completed!")


# ============================================================
# 14. MAKE PREDICTIONS
# ============================================================

y_pred = model.predict(X_test)

# Probability of heart disease
y_prob = model.predict_proba(X_test)[:, 1]


# ============================================================
# 15. CALCULATE ACCURACY
# ============================================================

accuracy = accuracy_score(
    y_test,
    y_pred
)

print(f"Accuracy: {accuracy:.4f}")


# ============================================================
# 16. CALCULATE ROC-AUC
# ============================================================

roc_auc = roc_auc_score(
    y_test,
    y_prob
)

print(f"ROC-AUC Score: {roc_auc:.4f}")


# ============================================================
# 17. CLASSIFICATION REPORT
# ============================================================

print("Classification Report:\n")

print(
    classification_report(
        y_test,
        y_pred,
        target_names=[
            "No Disease",
            "Disease"
        ]
    )
)


# ============================================================
# 18. CONFUSION MATRIX
# ============================================================

cm = confusion_matrix(
    y_test,
    y_pred
)

plt.figure(figsize=(6, 5))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=[
        "No Disease",
        "Disease"
    ],
    yticklabels=[
        "No Disease",
        "Disease"
    ]
)

plt.xlabel("Predicted Label")
plt.ylabel("Actual Label")
plt.title("Confusion Matrix")

plt.show()


# ============================================================
# 19. ROC CURVE
# ============================================================

RocCurveDisplay.from_predictions(
    y_test,
    y_prob
)

plt.title(
    "ROC Curve - Logistic Regression"
)

plt.show()


# ============================================================
# 20. FINAL HEART DISEASE RESULTS
# ============================================================

print("=" * 50)
print("HEART DISEASE PREDICTION RESULTS")
print("=" * 50)

print(f"\nAccuracy Score : {accuracy:.4f}")
print(f"ROC-AUC Score  : {roc_auc:.4f}")

print("\nClassification Report:")

print(
    classification_report(
        y_test,
        y_pred,
        target_names=[
            "No Disease",
            "Disease"
        ]
    )
)


# ============================================================
# 21. INSTALL WFDB FOR ECG ANALYSIS
# ============================================================

!pip install wfdb numpy pandas matplotlib


# ============================================================
# 22. IMPORT ECG LIBRARIES
# ============================================================

import wfdb
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# ============================================================
# 23. LOAD MIT-BIH ECG RECORD 100
# ============================================================

record = wfdb.rdrecord(
    "100",
    pn_dir="mitdb"
)

annotation = wfdb.rdann(
    "100",
    "atr",
    pn_dir="mitdb"
)


# ============================================================
# 24. ECG INFORMATION
# ============================================================

print(
    "Signal Shape:",
    record.p_signal.shape
)

print(
    "Sampling Frequency:",
    record.fs
)

print(
    "Signal Names:",
    record.sig_name
)

print("\nFirst 10 annotation samples:")

print(
    annotation.sample[:10]
)

print("\nFirst 10 annotation symbols:")

print(
    annotation.symbol[:10]
)


# ============================================================
# 25. EXTRACT ECG SIGNAL
# ============================================================

ec_signal = record.p_signal[:, 0]

fs = record.fs

print(
    "Total number of samples:",
    len(ecg_signal)
)

print(
    "Duration in seconds:",
    len(ecg_signal) / fs
)


# ============================================================
# 26. PLOT ECG SIGNAL
# ============================================================

start_time = 0
duration = 10

start_sample = int(
    start_time * fs
)

end_sample = int(
    (start_time + duration) * fs
)

time = (
    np.arange(
        start_sample,
        end_sample
    ) / fs
)

plt.figure(figsize=(15, 5))

plt.plot(
    time,
    ecg_signal[
        start_sample:end_sample
    ]
)

plt.xlabel("Time (seconds)")
plt.ylabel("Amplitude")

plt.title(
    "MIT-BIH Record 100 - ECG Signal"
)

plt.grid(True)

plt.show()


# ============================================================
# 27. ECG SIGNAL WITH BEAT ANNOTATIONS
# ============================================================

# Get all annotation sample locations
ann_samples = annotation.sample

# Get corresponding annotation symbols
ann_symbols = annotation.symbol

# Find annotations within selected segment
mask = (
    (ann_samples >= start_sample) &
    (ann_samples < end_sample)
)

segment_ann_samples = ann_samples[mask]

segment_ann_symbols = np.array(
    ann_symbols
)[mask]

# Convert annotation sample positions to time
segment_ann_times = (
    segment_ann_samples / fs
)

# ECG amplitude at annotation positions
segment_ann_amplitudes = (
    ecg_signal[
        segment_ann_samples
    ]
)

plt.figure(figsize=(15, 5))

# Plot ECG waveform
plt.plot(
    time,
    ecg_signal[
        start_sample:end_sample
    ],
    label="ECG Signal"
)

# Plot beat locations
plt.scatter(
    segment_ann_times,
    segment_ann_amplitudes,
    marker="o",
    label="Beat Annotation"
)

# Add beat symbols
for x, y_value, symbol in zip(
    segment_ann_times,
    segment_ann_amplitudes,
    segment_ann_symbols
):

    plt.text(
        x,
        y_value,
        symbol,
        fontsize=10
    )

plt.xlabel("Time (seconds)")
plt.ylabel("Amplitude")

plt.title(
    "ECG Signal with Beat Annotations"
)

plt.legend()
plt.grid(True)

plt.show()


# ============================================================
# 28. CREATE ECG ANNOTATION DATAFRAME
# ============================================================

annotations_df = pd.DataFrame({
    "sample": annotation.sample,
    "time_seconds": annotation.sample / fs,
    "beat_type": annotation.symbol
})

display(
    annotations_df.head(20)
)


# ============================================================
# 29. COUNT DIFFERENT BEAT TYPES
# ============================================================

beat_counts = (
    annotations_df["beat_type"]
    .value_counts()
)

print(beat_counts)


# ============================================================
# 30. EXTRACT NORMAL BEATS
# ============================================================

normal_beat_samples = annotations_df[
    annotations_df["beat_type"] == "N"
]["sample"].values

print(
    "Number of normal beats:",
    len(normal_beat_samples)
)


# ============================================================
# 31. CALCULATE RR INTERVALS
# ============================================================

rr_intervals = (
    np.diff(normal_beat_samples) / fs
)

print(
    "First 10 RR intervals:"
)

print(
    rr_intervals[:10]
)


# ============================================================
# 32. CALCULATE HEART RATE
# ============================================================

heart_rate = (
    60 / rr_intervals
)

print(
    "Mean Heart Rate:",
    np.mean(heart_rate)
)

print(
    "Median Heart Rate:",
    np.median(heart_rate)
)

print(
    "Minimum Heart Rate:",
    np.min(heart_rate)
)

print(
    "Maximum Heart Rate:",
    np.max(heart_rate)
)


# ============================================================
# 33. HEART RATE ANALYSIS SUMMARY
# ============================================================

print("=" * 45)
print("HEART RATE ANALYSIS")
print("=" * 45)

print(
    f"Number of Normal Beats: "
    f"{len(normal_beat_samples)}"
)

print(
    f"Number of RR Intervals: "
    f"{len(rr_intervals)}"
)

print(
    f"\nMean RR Interval: "
    f"{np.mean(rr_intervals):.3f} seconds"
)

print(
    f"Standard Deviation of RR: "
    f"{np.std(rr_intervals):.3f} seconds"
)

print(
    f"\nMean Heart Rate: "
    f"{np.mean(heart_rate):.2f} BPM"
)

print(
    f"Median Heart Rate: "
    f"{np.median(heart_rate):.2f} BPM"
)

print(
    f"Minimum Heart Rate: "
    f"{np.min(heart_rate):.2f} BPM"
)

print(
    f"Maximum Heart Rate: "
    f"{np.max(heart_rate):.2f} BPM"
)


# ============================================================
# 34. CALCULATE SDNN
# ============================================================

sdnn = np.std(
    rr_intervals,
    ddof=1
)

print(
    f"SDNN: {sdnn:.4f} seconds"
)


# ============================================================
# 35. CALCULATE RMSSD
# ============================================================

successive_diff = np.diff(
    rr_intervals
)

rmssd = np.sqrt(
    np.mean(
        successive_diff ** 2
    )
)

print(
    f"RMSSD: {rmssd:.4f} seconds"
)


# ============================================================
# 36. BASIC HRV STATISTICS
# ============================================================

print("=" * 45)
print("BASIC HRV STATISTICS")
print("=" * 45)

print(
    f"Mean RR Interval: "
    f"{np.mean(rr_intervals):.4f} sec"
)

print(
    f"SDNN: {sdnn:.4f} sec"
)

print(
    f"RMSSD: {rmssd:.4f} sec"
)


# ============================================================
# 37. VISUALIZE RR INTERVALS
# ============================================================

# Time location of each RR interval
rr_times = (
    normal_beat_samples[1:] / fs
)

# Basic statistics
mean_rr = np.mean(
    rr_intervals
)

std_rr = np.std(
    rr_intervals,
    ddof=1
)

# Create the plot
plt.figure(figsize=(16, 6))

# RR interval trend
plt.plot(
    rr_times,
    rr_intervals,
    marker="o",
    markersize=3,
    linewidth=1.2,
    alpha=0.8,
    label="RR Intervals"
)

# Mean RR interval
plt.axhline(
    mean_rr,
    linestyle="--",
    linewidth=2,
    label=f"Mean RR = {mean_rr:.3f} sec"
)

# Mean ± 1 Standard Deviation
plt.fill_between(
    rr_times,
    mean_rr - std_rr,
    mean_rr + std_rr,
    alpha=0.15,
    label="Mean ± 1 SD"
)

plt.title(
    "RR Interval Variability – MIT-BIH Record 100",
    fontsize=16,
    fontweight="bold",
    pad=15
)

plt.xlabel(
    "Time (seconds)",
    fontsize=12
)

plt.ylabel(
    "RR Interval (seconds)",
    fontsize=12
)

plt.grid(
    True,
    linestyle="--",
    alpha=0.5
)

plt.legend()

plt.tight_layout()

plt.show()


# ============================================================
# 38. UPLOAD CLINICAL NOTES
# ============================================================

from google.colab import files

uploaded = files.upload()


# ============================================================
# 39. READ CLINICAL NOTES
# ============================================================

with open(
    "clinical_note.txt",
    "r",
    encoding="utf-8"
) as file:

    clinical_notes = file.read()

print(
    "First 1000 characters:\n"
)

print(
    clinical_notes[:1000]
)


# ============================================================
# 40. IMPORT NLP LIBRARIES
# ============================================================

import re
import pandas as pd
import matplotlib.pyplot as plt

from collections import Counter


# ============================================================
# 41. TEXT CLEANING AND TOKENIZATION
# ============================================================

# Convert to lowercase
cleaned_text = clinical_notes.lower()

# Remove numbers and punctuation
cleaned_text = re.sub(
    r"[^a-z\s]",
    " ",
    cleaned_text
)

# Remove extra spaces
cleaned_text = re.sub(
    r"\s+",
    " ",
    cleaned_text
).strip()

# Tokenization
tokens = cleaned_text.split()

print(
    "Total Tokens:",
    len(tokens)
)

print(
    "\nFirst 30 Tokens:"
)

print(
    tokens[:30]
)


# ============================================================
# 42. REMOVE STOPWORDS
# ============================================================

stopwords = {
    "a", "an", "the", "and", "or", "of", "in", "on",
    "with", "to", "for", "is", "are", "was", "were",
    "has", "have", "had", "this", "that", "these",
    "those", "during", "after", "before", "from",
    "as", "at", "by", "be", "being", "been",
    "patient", "reports", "report", "presents",
    "includes", "include", "history", "medical",
    "further", "recommended", "advised"
}

filtered_tokens = [
    word
    for word in tokens
    if word not in stopwords
    and len(word) > 2
]

print(
    "Filtered Tokens:",
    len(filtered_tokens)
)

print("\nSample:")

print(
    filtered_tokens[:30]
)


# ============================================================
# 43. WORD FREQUENCY
# ============================================================

word_freq = Counter(
    filtered_tokens
)

word_freq_df = pd.DataFrame(
    word_freq.items(),
    columns=[
        "Word",
        "Frequency"
    ]
)

word_freq_df = word_freq_df.sort_values(
    by="Frequency",
    ascending=False
).reset_index(
    drop=True
)

display(
    word_freq_df.head(20)
)


# ============================================================
# 44. TOP 15 WORDS VISUALIZATION
# ============================================================

top_words = (
    word_freq_df
    .head(15)
    .sort_values("Frequency")
)

plt.figure(figsize=(12, 7))

bars = plt.barh(
    top_words["Word"],
    top_words["Frequency"]
)

# Add frequency labels
for bar in bars:

    width = bar.get_width()

    plt.text(
        width + 1,
        bar.get_y() +
        bar.get_height() / 2,
        str(int(width)),
        va="center",
        fontweight="bold"
    )

plt.title(
    "Top 15 Most Frequent Terms in Clinical Notes",
    fontsize=16,
    fontweight="bold",
    pad=15
)

plt.xlabel("Frequency")
plt.ylabel("Terms")

plt.grid(
    axis="x",
    linestyle="--",
    alpha=0.4
)

plt.tight_layout()

plt.show()


# ============================================================
# 45. CLINICAL KEYWORDS
# ============================================================

clinical_keywords = [
    "chest pain",
    "chest discomfort",
    "chest pressure",
    "chest tightness",
    "shortness of breath",
    "hypertension",
    "cholesterol",
    "fatigue",
    "dizziness",
    "palpitations",
    "diabetes",
    "ecg",
    "cardiac",
    "cardiovascular",
    "exercise tolerance"
]


# ============================================================
# 46. COUNT CLINICAL TERMS
# ============================================================

note_lower = clinical_notes.lower()

clinical_term_counts = {
    term: note_lower.count(term)
    for term in clinical_keywords
}

# Convert to DataFrame
term_df = pd.DataFrame(
    clinical_term_counts.items(),
    columns=[
        "Clinical Term",
        "Frequency"
    ]
)

# Keep only detected terms
term_df = term_df[
    term_df["Frequency"] > 0
].sort_values(
    "Frequency",
    ascending=False
).reset_index(
    drop=True
)

display(term_df)


# ============================================================
# 47. CLINICAL TERMS VISUALIZATION
# ============================================================

plot_df = term_df.sort_values(
    "Frequency"
)

plt.figure(figsize=(12, 7))

bars = plt.barh(
    plot_df["Clinical Term"],
    plot_df["Frequency"]
)

# Add value labels
for bar in bars:

    width = bar.get_width()

    plt.text(
        width + 1,
        bar.get_y() +
        bar.get_height() / 2,
        f"{int(width)}",
        va="center",
        fontweight="bold"
    )

plt.title(
    "Frequency of Key Clinical Terms",
    fontsize=16,
    fontweight="bold",
    pad=15
)

plt.xlabel("Number of Occurrences")
plt.ylabel("Clinical Terms")

plt.grid(
    axis="x",
    linestyle="--",
    alpha=0.4
)

plt.tight_layout()

plt.show()


# ============================================================
# 48. SPLIT CLINICAL NOTES
# ============================================================

notes = re.split(
    r"NOTE \d+",
    clinical_notes
)

notes = [
    note.strip()
    for note in notes
    if note.strip()
]

print(
    f"Total Patient Notes: {len(notes)}"
)


# ============================================================
# 49. PATIENT-WISE CLINICAL TERM EXTRACTION
# ============================================================

patient_results = []

for note in notes:

    # Extract Patient ID
    patient_id_match = re.search(
        r"Patient ID:\s*(P\d+)",
        note
    )

    patient_id = (
        patient_id_match.group(1)
        if patient_id_match
        else "Unknown"
    )

    # Find clinical keywords
    found_terms = [
        term
        for term in clinical_keywords
        if term in note.lower()
    ]

    patient_results.append({
        "Patient ID": patient_id,
        "Clinical Terms Detected":
            ", ".join(found_terms),
        "Number of Terms":
            len(found_terms)
    })

patient_df = pd.DataFrame(
    patient_results
)

display(
    patient_df.head(10)
)


# ============================================================
# 50. TEXTUAL DATA SUMMARY
# ============================================================

print("=" * 55)
print(
    "TEXTUAL DATA / SIMPLE NLP ANALYSIS SUMMARY"
)
print("=" * 55)

print(
    f"\nTotal Clinical Notes: {len(notes)}"
)

print(
    f"Total Tokens: {len(tokens)}"
)

print(
    f"Filtered Tokens: {len(filtered_tokens)}"
)

print(
    f"Unique Terms: "
    f"{len(set(filtered_tokens))}"
)

print(
    "\nTop 10 Most Frequent Words:"
)

for word, count in word_freq.most_common(10):

    print(
        f"{word:<20} : {count}"
    )

print(
    "\nTop Clinical Terms:"
)

print(
    term_df.head(10).to_string(
        index=False
    )
)


# ============================================================
# 51. UPLOAD CHEST X-RAY IMAGE
# ============================================================

from google.colab import files

uploaded = files.upload()


# ============================================================
# 52. IMPORT IMAGE LIBRARIES
# ============================================================

from PIL import Image

import matplotlib.pyplot as plt


# ============================================================
# 53. LOAD CHEST X-RAY
# ============================================================

image = Image.open(
    "chest_xray.jpg"
)

print(
    "Image loaded successfully!"
)


# ============================================================
# 54. EXTRACT IMAGE METADATA
# ============================================================

print(
    "Image Format:",
    image.format
)

print(
    "Image Mode:",
    image.mode
)

print(
    "Image Size:",
    image.size
)

width, height = image.size

print(
    "Width:",
    width
)

print(
    "Height:",
    height
)


# ============================================================
# 55. CALCULATE ASPECT RATIO
# ============================================================

aspect_ratio = (
    width / height
)

print(
    f"Aspect Ratio: "
    f"{aspect_ratio:.2f}"
)


# ============================================================
# 56. DISPLAY ORIGINAL IMAGE
# ============================================================

plt.figure(
    figsize=(8, 8)
)

plt.imshow(
    image,
    cmap="gray"
)

plt.title(
    f"Original Medical Image "
    f"({width} × {height})",
    fontsize=14,
    fontweight="bold"
)

plt.axis("off")

plt.show()


# ============================================================
# 57. RESIZE IMAGE
# ============================================================

resized_image = image.resize(
    (224, 224)
)

print(
    "Resized Image Size:",
    resized_image.size
)


# ============================================================
# 58. DISPLAY ORIGINAL AND RESIZED IMAGE
# ============================================================

plt.figure(
    figsize=(12, 6)
)

# Original image
plt.subplot(1, 2, 1)

plt.imshow(
    image,
    cmap="gray"
)

plt.title(
    "Original Image"
)

plt.axis("off")


# Resized image
plt.subplot(1, 2, 2)

plt.imshow(
    resized_image,
    cmap="gray"
)

plt.title(
    "Resized Image (224 × 224)"
)

plt.axis("off")

plt.tight_layout()

plt.show()


# ============================================================
# 59. CONVERT IMAGE TO NUMPY ARRAY
# ============================================================

import numpy as np

image_array = np.array(
    resized_image
)

print(
    "Image Array Shape:",
    image_array.shape
)

print(
    "Data Type:",
    image_array.dtype
)

print(
    "Minimum Pixel Value:",
    image_array.min()
)

print(
    "Maximum Pixel Value:",
    image_array.max()
)


# ============================================================
# 60. NORMALIZE IMAGE
# ============================================================

normalized_image = (
    image_array / 255.0
)

print(
    "Normalized Pixel Range:"
)

print(
    "Minimum:",
    normalized_image.min()
)

print(
    "Maximum:",
    normalized_image.max()
)